### ISSUE TITLE
Make Worker Resources Configurable

### ISSUE THREAD

**Issue by benjigoldberg** [bloomberg/airflow#22]
We should probably add the ability for users to define worker config. I wonder if this should be something that can be configured on a task basis rather than in the config? Though to be fair if you have large batch workloads I'm not sure that Airflow should instead be triggering some other more appropriate data tool.

@dimberman @grantnicholas what do you think?

**Comment by grantnicholas** [comment]
I think this is duplicated here:

https://github.com/bloomberg/airflow/issues/3

**Comment by benjigoldberg** [comment]
You're right @grantnicholas closing this out
